#' @importFrom kwb.kuras.db anzahlIndikatorenProEffekt
#' @importFrom kwb.kuras.db anzahlWerteProIndikator
#' @importFrom kwb.kuras.db beispielAuswertung.1
#' @importFrom kwb.kuras.db kuras_anlageeigenschaft
#' @importFrom kwb.kuras.db kuras_anlageeigenschaftswert
#' @importFrom kwb.kuras.db kuras_anlageoderstudie
#' @importFrom kwb.kuras.db kuras_effekt
#' @importFrom kwb.kuras.db kuras_indikator
#' @importFrom kwb.kuras.db kuras_indikatorwert
#' @importFrom kwb.kuras.db kuras_institution
#' @importFrom kwb.kuras.db kuras_kommentar
#' @importFrom kwb.kuras.db kuras_koordinatensystem
#' @importFrom kwb.kuras.db kuras_massnahmeebene
#' @importFrom kwb.kuras.db kuras_massnahmenkategorie
#' @importFrom kwb.kuras.db kuras_massnahmetyp
#' @importFrom kwb.kuras.db kuras_person
#' @importFrom kwb.kuras.db kuras_projekt
#' @importFrom kwb.kuras.db kuras_referenz
#' @importFrom kwb.kuras.db kuras_referenzgruppe
#' @importFrom kwb.kuras.db kuras_referenzgruppereferenz
#' @importFrom kwb.kuras.db kuras_standort

# readKurasSamplerFileByName ---------------------------------------------------
NULL

#' Read KURAS Sampler File by Name
#' 
#' @param samplerFile path to file written by autosampler
#' @param bottlesToConsider arguments passed to
#'   \code{\link{generateSampleTimesFromFlaschenbericht}}
#' @importFrom kwb.ogre readOgreSamplerFileByName
#' @export
readKurasSamplerFileByName <- function(samplerFile, bottlesToConsider = NA)
{
  if (grepl("_R\\.csv$", samplerFile)) {
    
    cat("Expecting file format as generated by", 
        "'KURAS_convertAutosamplerFiles_RBFAB.R': ")
    
    content <- readKurasSamplerFileByName.R(samplerFile)
   
    # introduce a column containing the file name
    content$samplerFile = basename(samplerFile)
    
    kwb.monitoring:::filterForRelevantBottles(content, bottlesToConsider)  
    
  } else {
    
    cat("Expecting file format as generated by 'Hach Sigma SD900': ")
    
    kwb.ogre::readOgreSamplerFileByName(samplerFile, bottlesToConsider)
  }
}

# readKurasSamplerFileByName.R -------------------------------------------------

#' Read KURAS Sampler File by Name
#' 
#' Read file generated by KURAS_convertAutosamplerFiles_RBFAB.R from 
#'   "_flaschenbericht" file
#' 
#' @param samplerFile path to file written by autosampler
#' @export
#' 
readKurasSamplerFileByName.R <- function(samplerFile)
{
  cat("Reading sample data from", basename(samplerFile), "... ")
  
  content <- utils::read.csv(
    samplerFile, 
    comment.char = "#", 
    header = TRUE, 
    stringsAsFactors = FALSE
  )
  
  cat("ok.\n")
  
  content
}

# generateSampleTimesFromFlaschenbericht ---------------------------------------

#' Generate Sample Times From Flaschenbericht
#' 
#' Generate equidistant sample times from the informatin given in the
#'   "Flaschenbericht"
#' 
#' @param content data frame with columns \code{timeFrom}, \code{timeTo},
#'   \code{pnSoll}, \code{pnIst},
#' @param text.success text to be put in output column \code{result} in case of
#'   success
#' @param text.failure text to be put in output column \code{result} in case of
#'   failure
#' @importFrom kwb.utils checkForMissingColumns
#' @export
generateSampleTimesFromFlaschenbericht <- function(
  content, text.success = "SUCCESS", text.failure = "FAILURE"  
)
{
  singleSamples.all <- NULL
  sampleCount <- 0
  
  kwb.utils::checkForMissingColumns(content, c(
    "bottle", "timeFrom", "timeTo", "pnSoll", "pnIst"
  ))
  
  for (i in seq_len(nrow(content))) {
    
    timediff <- as.integer(content$timeTo[i]) - as.integer(content$timeFrom[i])
    
    n <- content$pnSoll[i]
    
    timestep <- timediff / n
    
    singleSamples <- data.frame(
      
      sampleTime = content$timeFrom[i] + 
        (seq_len(n) - 1) * timestep + timestep / 2,
      
      # subsample = seq_len(n),
      
      sample = seq_len(n) + sampleCount,
      
      bottle = content$bottle[i],
      
      # introduce column "result" containing "SUCCESS" for the first <pnIst>
      # samples and "FAILURE" for the remaining samples
      result = ifelse(
        seq_len(n) <= content$pnIst[i], text.success, text.failure
      ),
      
      stringsAsFactors = FALSE
    )
    
    singleSamples.all <- rbind(singleSamples.all, singleSamples)    
    
    sampleCount <- sampleCount + n    
  }
  
  singleSamples.all  
}
